export const routePaths = {
  home: '/',
  login: '/login',
  register: '/register',
  studentDashboard: '/student/dashboard',
  studentGames: '/student/games',
  studentTasks: '/student/tasks',
  teacherDashboard: '/teacher/dashboard',
  teacherClassroom: '/teacher/classroom',
  teacherQuestions: '/teacher/questions',
  bombGame: '/games/bomb-game',
  avoidGermsGame: '/games/avoid-germs',
  bankPanicGame: '/games/bank-panic',
  breakoutGame: '/games/breakout',
  cardMemoryGame: '/games/card-memory',
  emojiMatchGame: '/games/emoji-match',
  slidingPuzzleGame: '/games/sliding-puzzle',
  snakeGame: '/games/snake',
  snowmenAttackGame: '/games/snowmen-attack',
  stackerGame: '/games/stacker',
  tomGame: '/games/tom',
} as const;
